# NumPy

This shall give you an idea of the intricacies in this library and will make you appreciate why NumPy is soo useful. 

In [2]:
import numpy as np

## Vectorization

NumPy vectorization involves performing mathematical operations on entire
arrays, eliminating the need to loop through individual elements.

Let's compare the execution times of a non-vectorized program and a vectorized one.

Your goal is to multiply each element of the 2D arrays by 3. Implement this using both non-vectorized and vectorized approaches.



In [ ]:
import time

arr_nonvectorized = np.random.rand(1000, 1000)
arr_vectorized = np.array(arr_nonvectorized) # making a deep copy of the array https://stackoverflow.com/questions/184710/what-is-the-difference-between-a-deep-copy-and-a-shallow-copy

start_nv = time.time()

# Non-vectorized approach
# <START>
for x in range(arr_nonvectorized.shape[0]):
    for y in range(arr_nonvectorized.shape[1]):
        arr_nonvectorized[x,y]*=3
# <END>

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")

start_v = time.time()

# Vectorized approach
# <START>
arr_vectorized*=3
# <END>

end_v = time.time()
print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(np.allclose(arr_nonvectorized, arr_vectorized))

Time taken in non-vectorized approach: 370.37158012390137 ms
Time taken in vectorized approach: 1.0216236114501953 ms


Perform Matrix Multiplication of A and B using vectorized and non-vectorized means and observe the time difference.

In [ ]:
# Generate two random 500x500 matrices
A = np.random.rand(500, 500)
B = np.random.rand(500, 500)

# Non-vectorized matrix multiplication
C_nonvectorized = np.zeros((500, 500))  # Initialize result matrix
start_nv = time.time()

# <START: Non-vectorized approach>
for i in range(500):
    for j in range(500):
        for k in range(500):
            C_nonvectorized[i,j]+=A[i,k]*B[k,j]
# <END>

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000 * (end_nv - start_nv), "ms")

# Vectorized matrix multiplication
start_v = time.time()

# <START: Vectorized approach>
# C_nonvectorized=np.dot(A,B)
C_nonvectorized=A@B
# <END>

end_v = time.time()
print("Time taken in vectorized approach:", 1000 * (end_v - start_v), "ms")

# Uncomment and execute the below line to verify both approaches give the same result
# print(np.allclose(C_nonvectorized, C_vectorized))

Time taken in non-vectorized approach: 64876.49440765381 ms
Time taken in vectorized approach: 4.245996475219727 ms


Vectorization uses NuPy's low level operations to speed things up. Make sure you know why!

### :\\/: *no for loops alllowed  hereafter* :\\/:

## Broadcasting

You are given a set of 5 2D points as an ndarray and you want to compute the euclidean distance between each pair of points and store it into a 5*5 ndarray.

*Hint: use the* `np.linalg.norm()` *function for this*

In [ ]:
import numpy as np

# Generate a random 5x2 array of points (values between 0 and 10)
points = np.random.rand(5, 2) *10
print("2D Points:\n", points)

# Task: Compute pairwise Euclidean distances using broadcasting
# <START: Pairwise distance computation>
distance_matrix = np.linalg.norm(points[np.newaxis,:]-points[:,np.newaxis], axis=2) # Replace with broadcasting operation
# <END>

#  Print the distance matrix
print("Pairwise Euclidean Distance Matrix:\n", distance_matrix)


2D Points:
 [[6.50286856 0.97819666]
 [5.87422798 5.37384428]
 [4.01666941 6.71804427]
 [8.61858463 6.0427747 ]
 [1.89731422 9.74979995]]
Pairwise Euclidean Distance Matrix:
 [[0.         4.4403724  6.25516081 5.4887344  9.90717695]
 [4.4403724  0.         2.29290154 2.82470552 5.91310672]
 [6.25516081 2.29290154 0.         4.65119475 3.69908217]
 [5.4887344  2.82470552 4.65119475 0.         7.67577436]
 [9.90717695 5.91310672 3.69908217 7.67577436 0.        ]]


In [44]:
# 2 x 5 x 5
(9.71911312 - 4.1080346)**2 + (6.53592428-5.63094852)**2

32.30318328379296